In [1]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in d:\python\lib\site-packages (2.1.1)
Requirement already satisfied: pandas in d:\python\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in d:\python\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\python\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in d:\python\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in d:\python\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
e_data=pd.read_excel("employee_data.xlsx")
e_data

   EmployeeID  Name Department  Salary  Experience (Years)  Age
0         201  John         HR   50000                   2   25
1         202  Lily    Finance   65000                   5   32
2         203   Sam         IT   70000                   3   28
3         204  Nina         IT   72000                   4   30
4         205  Mike    Finance   68000                   6   35
5         206  Tara         HR   48000                   1   24
6         207   Raj         IT   71000                   4   29

In [4]:
e_data.shape

(7, 6)

In [5]:
e_data.isnull().sum()

EmployeeID            0
Name                  0
Department            0
Salary                0
Experience (Years)    0
Age                   0
dtype: int64

In [6]:
e_data['Salary'].mean()

63428.57142857143

In [8]:
group_dept=e_data.groupby('Department')
group_dept['Salary'].mean()

Department
Finance    66500.0
HR         49000.0
IT         71000.0
Name: Salary, dtype: float64

In [9]:
group_dept['Experience (Years)'].mean()

Department
Finance    5.500000
HR         1.500000
IT         3.666667
Name: Experience (Years), dtype: float64

In [11]:
e_data[e_data['Salary']>65000]['Name']

2     Sam
3    Nina
4    Mike
6     Raj
Name: Name, dtype: object

In [23]:
IT_emp=e_data[e_data['Department']=='IT']
you_IT_emp=IT_emp[IT_emp['Age']==IT_emp['Age'].min()]
you_IT_emp

   EmployeeID Name Department  Salary  Experience (Years)  Age
2         203  Sam         IT   70000                   3   28

In [25]:
e_data['Seniority']=e_data['Experience (Years)'].apply(lambda x: "Senior" if x >=5 else 'Junior')
e_data

   EmployeeID  Name Department  Salary  Experience (Years)  Age Seniority
0         201  John         HR   50000                   2   25    Junior
1         202  Lily    Finance   65000                   5   32    Senior
2         203   Sam         IT   70000                   3   28    Junior
3         204  Nina         IT   72000                   4   30    Junior
4         205  Mike    Finance   68000                   6   35    Senior
5         206  Tara         HR   48000                   1   24    Junior
6         207   Raj         IT   71000                   4   29    Junior

In [26]:
e_data.sort_values('Salary',ascending=False)
e_data

   EmployeeID  Name Department  Salary  Experience (Years)  Age Seniority
0         201  John         HR   50000                   2   25    Junior
1         202  Lily    Finance   65000                   5   32    Senior
2         203   Sam         IT   70000                   3   28    Junior
3         204  Nina         IT   72000                   4   30    Junior
4         205  Mike    Finance   68000                   6   35    Senior
5         206  Tara         HR   48000                   1   24    Junior
6         207   Raj         IT   71000                   4   29    Junior

In [28]:
e_data.to_csv("modified_employee_data",index=False)