In [1]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in d:\python\lib\site-packages (2.1.1)
Requirement already satisfied: pandas in d:\python\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in d:\python\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\python\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in d:\python\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in d:\python\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
s_data=pd.read_excel("student_scores.xlsx")
s_data

   StudentID     Name  Subject  Score Grade  Attendance (%)
0        101    Alice     Math     88     B              95
1        102      Bob     Math     76     C              82
2        103  Charlie  Science     93     A              98
3        104    David     Math     65     D              70
4        105      Eva  Science     85     B              90
5        106    Frank     Math     90     A              97
6        107    Grace  Science     72     C              88
7        108    Helen  Science     95     A              99

2. Display basic information about the dataset

Number of rows and columns

Data types

Missing values

In [7]:
s_data.shape

(8, 6)

In [9]:
s_data.dtypes

StudentID          int64
Name              object
Subject           object
Score              int64
Grade             object
Attendance (%)     int64
dtype: object

In [15]:
s_data.isnull().sum()

StudentID         0
Name              0
Subject           0
Score             0
Grade             0
Attendance (%)    0
dtype: int64

In [19]:
s_data[s_data['Score']>85][['Name',"Score"]]

      Name  Score
0    Alice     88
2  Charlie     93
5    Frank     90
7    Helen     95

In [23]:
subgrp=s_data.groupby('Subject')
subgrp['Score'].mean()

Subject
Math       79.75
Science    86.25
Name: Score, dtype: float64

In [28]:
gradgrp=s_data.groupby('Grade')
gradgrp.size()

Grade
A    3
B    2
C    2
D    1
dtype: int64

In [30]:
s_data['Grade'].value_counts()

Grade
A    3
B    2
C    2
D    1
Name: count, dtype: int64

In [33]:
s_data[s_data['Attendance (%)'] == s_data['Attendance (%)'].max()][['Name','Attendance (%)']]

    Name  Attendance (%)
7  Helen              99

In [36]:
s_data['Result']=s_data['Score'].apply(lambda x: 'Pass' if x>=75 else 'Fail')
s_data

   StudentID     Name  Subject  Score Grade  Attendance (%) Result
0        101    Alice     Math     88     B              95   Pass
1        102      Bob     Math     76     C              82   Pass
2        103  Charlie  Science     93     A              98   Pass
3        104    David     Math     65     D              70   Fail
4        105      Eva  Science     85     B              90   Pass
5        106    Frank     Math     90     A              97   Pass
6        107    Grace  Science     72     C              88   Fail
7        108    Helen  Science     95     A              99   Pass

In [41]:
s_data.sort_values('Score',ascending=False,inplace=True)
s_data

   StudentID     Name  Subject  Score Grade  Attendance (%) Result
7        108    Helen  Science     95     A              99   Pass
2        103  Charlie  Science     93     A              98   Pass
5        106    Frank     Math     90     A              97   Pass
0        101    Alice     Math     88     B              95   Pass
4        105      Eva  Science     85     B              90   Pass
1        102      Bob     Math     76     C              82   Pass
6        107    Grace  Science     72     C              88   Fail
3        104    David     Math     65     D              70   Fail

In [40]:
s_data.to_csv('modified_student_scores.csv', index=False)